# 项目信息
site_name: virbit
site_description: virbit 是教程文档，beanflame哲学研究教程文档设计工程计划，尝试写得很细，语言要通俗易懂，希望能够建立起一个完善的教程。
site_author: beanflame
# site_url: https://oi-wiki.org
strict: false

# 存储库
repo_name: 'beanflame/virbit'
repo_url: 'https://github.com/beanflame/virbit'
edit_uri: 'https://oi-wiki.org/edit-landing/?ref='



# 版权
copyright: 'Copyright &copy; 2021 - 2021 virbit'
google_analytics:
  - 'UA-124485594-1'
  - 'auto'


# 目录
nav:
  - virbit官网:
    - 主页: 'index.md'
    - 主题: 'theme.md'
  - OpenGL教程:
    - 主页: 'opengl-book/index.md'
    - 简介: 'opengl-book/intro.md'
    - 入门:
      - OpenGL: 'opengl-book/1-introduction/1-OpenGL.md'
      - OpenGL配置: 'opengl-book/1-introduction/2-OpenGL-Configuration.md'
      - 创建窗口: 'opengl-book/1-introduction/3-Create-Window.md'
    
    
  
  
#  - 简介:
#    - Getting Started: index.md
#    - 关于本项目: intro/about.md
#    - 如何参与: intro/htc.md
#    - 格式手册: intro/format.md
#    - F.A.Q.: intro/faq.md
#    - 用 Docker 部署 OI Wiki: intro/docker-deploy.md
#    - 致谢: intro/thanks.md

# 主题
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# 定制
extra:
  search:
    language: 'zh'
  disqus: 'virbit'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  # notice:
  #   title: 'Hi'
  #   message: '欢迎点击这里对 OI Wiki 提一点建议'
  #   url: 'https://wj.qq.com/s2/4467592/b1e9'
  #   position: 'topCenter'
  #   progressBar: false
  #   timeout: false


extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - '_static/css/extra.css?v=13'

# 扩展
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
